name: generate-snake-game

on:
  schedule:
    - cron: "0 0 * * *"  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar animação da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: GabrielCotrimMiron
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg

      - name: Enviar para o branch output
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
